name: Code Checks
on: push
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-route
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules-v1
        with:
          path: ${{ steps.pnpm-route.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install Node modules
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Run Svelte Check
        run: pnpm check

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run tests
        run: npx playwright install && pnpm test
